### ISSUE TITLE
New version won't save settings in chrome

### ISSUE THREAD

**Issue by MuddyPuddles** [amshove/GC_little_helper#140] opened 2015-03-22 21:13 UTC
New version 11.4 will not allow saving of settings in chrome. I can edit the settings but they won't save and simply change back as soon as I press save. If I can't choose my settings gclh is no use to me. Previous version was excellent, now it's broken.

**Comment by xiefehl** [comment] 2015-03-23 08:15
Indeed. All my composed  signaturesare gone and new ones not accepted.!! HELPPPPPP Plz.

**Comment by lukeIam** [comment] 2015-03-23 10:45
Confirmed!
Sorry for that - I'll investigate the reason.

It's strange: The git version works well for me but the packed version fails (and it seems there are no differences in the source files)

**Comment by lukeIam** [comment] 2015-03-23 10:56
> EDIT: after deleting all extension settings and reinstallation of gclh the problem also occurs with the unpacked version.

Nope, I only reached "MAX_WRITE_OPERATIONS_PER_MINUTE"

**Comment by lukeIam** [comment] 2015-03-23 11:28
Hmm - Now the chrome store version works without any problem again...

Maybe quota is also the reason here...

**Comment by lukeIam** [comment] 2015-03-23 12:01
Backup your Data before using this quick fix! 

For a release version I'll have to search for a reliable migration mechanism or decrease the numbers of storage set calls.

**Comment by MuddyPuddles** [comment] 2015-03-23 15:16
Yep, uninstalled it, reinstalled from Google Chrome store and it's all working again. Settings stay changed. Many thanks, whatever you did worked.

**Comment by lukeIam** [comment] 2015-03-23 15:44
@MuddyPuddles I did't update the extension in the Google Chrome store.
(So it seems that there is a quota problem)

**Comment by Cappa-d** [comment] 2015-03-24 19:41
hmmm all lost here as well. Even while partially it seems to be ok again the VIP list does not work. It got deleted and building it again does not store the seleteced people

**Comment by lukeIam** [comment] 2015-03-24 21:53
Current workarounds:

- https://github.com/amshove/GC_little_helper/commit/5d1920e3f54b8ddcc03425418d83878518107935 (Backup your data!)

or

- As this seems to be a quota per minute problem wait some time an try to save the settings again

**Comment by lukeIam** [comment] 2015-03-24 22:13
@Torsten- Do you know where we do so much write operations?
MAX_WRITE_OPERATIONS_PER_MINUTE is 120 which should be a lot...

**Comment by lukeIam** [comment] 2015-03-24 22:28
@all Do you have `Auto apply DB-config` turned on?

**Comment by Cappa-d** [comment] 2015-03-25 09:37
Well I had DB-config turned on yes. I am configuring again without this option

**Comment by Cappa-d** [comment] 2015-03-25 09:43
hmmm trying to set the settings again resulted in nothing.. not possible to save it.

Will delete the extension and try again

**Comment by Cappa-d** [comment] 2015-03-25 10:11
ok deleted the extension and installed it agai. Actually NOTHING is saved. Whatever I change it will not work

**Comment by lukeIam** [comment] 2015-03-25 10:28
@Cappa-d can you may check something for me?

- open `chrome://extensions/`
- search for `GC little helper`
- click on `Inspect views: background page`
- go to the `Console` tab
- tick `Presevere log`
- try to save some settings
- check what error messages appear in the console

**Comment by Hobo2k** [comment] 2015-03-25 10:33
Hi,

I only have the message:

Unchecked runtime.lastError while running storage.set: QUOTA_BYTES_PER_ITEM quota exceeded
    at chrome-extension://aimnideehoepfoiniigacdpefnlngnob/chromeStorage.js:10:23extensions::sendRequest:82 handleResponse

**Comment by Cappa-d** [comment] 2015-03-25 10:41
hmm strange actualy nothing is shown there....

**Comment by lukeIam** [comment] 2015-03-25 10:46
@Hobo2k Oh THAT makes sene: we only have 8KB per Item and 100KB total.
The problem here is that GClh stores all settings in one value.
I guess you have templates defined -> so we reach the 8KB limit

Thanks for your input -> I'll try to find some solution this evening...

**Comment by lukeIam** [comment] 2015-03-25 10:47
@Cappa-d And in the normal console? 

On the geocaching.com site press `Strg + Shift + I`

**Comment by Cappa-d** [comment] 2015-03-25 10:48
debug: Setting indexRepaired to new value: 77
info: Enabling export to other scripts
debug: found URL: http://www.geocaching.com/my/#
debug: matched gccommentOnProfilePage
info: weaving comments into table...
GM_registerMenuCommand is not supported.
Refused to set unsafe header "User-Agent" (index):1
GM_registerMenuCommand is not supported.
GClh_ERROR - Check for Updates - http://www.geocaching.com/my/#: Cannot read property '2' of null
Stacktrace:
TypeError: Cannot read property '2' of null
    at GM_xmlhttpRequest.onload (chrome-extension://aimnideehoepfoiniigacdpefnlngnob/gc_little_helper.js:7023:56)
    at XMLHttpRequest.xhr.(anonymous function) (<anonymous>:37:7)
GClh_ERROR - Check for Updates - http://www.geocaching.com/my/#: Cannot read property '2' of null
Stacktrace:
TypeError: Cannot read property '2' of null
    at GM_xmlhttpRequest.onload (chrome-extension://aimnideehoepfoiniigacdpefnlngnob/gc_little_helper.js:7023:56)
    at XMLHttpRequest.xhr.(anonymous function) (<anonymous>:37:7)

**Comment by Cappa-d** [comment] 2015-03-25 10:49
strange enough even while HZ coordinates are set they are not retrieved by GClh

**Comment by Cappa-d** [comment] 2015-03-25 10:50
debug: Setting indexRepaired to new value: 77 VM1397:55
info: Enabling export to other scripts VM1397:55
debug: found URL: http://www.geocaching.com/my/# VM1397:55
debug: matched gccommentOnProfilePage VM1397:55
info: weaving comments into table... VM1397:55
Denying load of chrome-extension://aimnideehoepfoiniigacdpefnlngnob/dropbox.min.map. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension. (index):1
GM_registerMenuCommand is not supported. VM1400:74
Refused to set unsafe header "User-Agent" VM1400:57
GM_registerMenuCommand is not supported. VM1400:74
Denying load of chrome-extension://ibljihldcopifedhilinmjdcanddolpb/dropbox.min.map. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension. (index):1
GClh_ERROR - Check for Updates - http://www.geocaching.com/my/#: Cannot read property '2' of null
Stacktrace:
TypeError: Cannot read property '2' of null
    at GM_xmlhttpRequest.onload (chrome-extension://aimnideehoepfoiniigacdpefnlngnob/gc_little_helper.js:7023:56)
    at XMLHttpRequest.xhr.(anonymous function) (<anonymous>:37:7) gc_little_helper.js:7394
GClh_ERROR - Check for Updates - http://www.geocaching.com/my/#: Cannot read property '2' of null
Stacktrace:
TypeError: Cannot read property '2' of null
    at GM_xmlhttpRequest.onload (chrome-extension://aimnideehoepfoiniigacdpefnlngnob/gc_little_helper.js:7023:56)
    at XMLHttpRequest.xhr.(anonymous function) (<anonymous>:37:7)

**Comment by lukeIam** [comment] 2015-03-25 10:54
@Cappa-d your log looks good - the `GClh_ERROR - Check for Updates` is normal in chrome (to be fixed sometime in future...) but the error is catched and do not harm the script execution. 

==>It should work...

**Comment by Hobo2k** [comment] 2015-03-25 10:57
My Log:

Navigated to http://www.geocaching.com/my/
modernizer?v=wa97G2fdGaWBnIjKyioUssAWxy8tnYxkV0d-_5ClId01:1 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.
gpt.js:87 GET http://tpc.googlesyndication.com/safeframe/1-0-2/html/container.html net::ERR_BLOCKED_BY_CLIENT
gpt.js:48 GET http://partner.googleadservices.com/gpt/pubads_impl_58.js net::ERR_BLOCKED_BY_CLIENT
VM752:74 GM_registerMenuCommand is not supported.
VM752:74 GM_registerMenuCommand is not supported.
gcvote.js:352 GET http://dl.dropbox.com/s/ttvxvywl493dljq/gcVoteIconData.json 403 (URLBlocked)
(index):1 Denying load of chrome-extension://aimnideehoepfoiniigacdpefnlngnob/dropbox.min.map. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
Navigated to http://www.geocaching.com/my/
modernizer?v=wa97G2fdGaWBnIjKyioUssAWxy8tnYxkV0d-_5ClId01:1 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.
gpt.js:87 GET http://tpc.googlesyndication.com/safeframe/1-0-2/html/container.html net::ERR_BLOCKED_BY_CLIENT
gpt.js:48 GET http://partner.googleadservices.com/gpt/pubads_impl_58.js net::ERR_BLOCKED_BY_CLIENT
VM1042:74 GM_registerMenuCommand is not supported.
VM1042:74 GM_registerMenuCommand is not supported.
gcvote.js:352 GET http://dl.dropbox.com/s/ttvxvywl493dljq/gcVoteIconData.json 403 (URLBlocked)
(index):1 Denying load of chrome-extension://aimnideehoepfoiniigacdpefnlngnob/dropbox.min.map. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.


I'm behind a proxy server, which blocks something ;-)

**Comment by lukeIam** [comment] 2015-03-25 11:02
@Hobo2k Only messages by GCVote

OT: You are blocking the url with the addional icons :wink: 
But this should be optional for GCVote.

**Comment by Hobo2k** [comment] 2015-03-25 11:19
More messages didn't apear.

**Comment by Cappa-d** [comment] 2015-03-25 11:32
Well I try again later with a different PC.

**Comment by Cappa-d** [comment] 2015-03-25 20:46
ok tested at other PC:

extensions::sendRequest:82 Unchecked runtime.lastError while running storage.set: This request exceeds the MAX_WRITE_OPERATIONS_PER_MINUTE quota.
    at chrome-extension://aimnideehoepfoiniigacdpefnlngnob/chromeStorage.js:10:23extensions::sendRequest:82 handleResponse
Navigated to chrome-extension://aimnideehoepfoiniigacdpefnlngnob/_generated_background_page.html
54extensions::sendRequest:82 Unchecked runtime.lastError while running storage.set: QUOTA_BYTES_PER_ITEM quota exceeded
    at chrome-extension://aimnideehoepfoiniigacdpefnlngnob/chromeStorage.js:10:23extensions::sendRequest:82 handleResponse
4Navigated to chrome-extension://aimnideehoepfoiniigacdpefnlngnob/_generated_background_page.html

- I have no templates in use
- VIP list even while it was selected not updated and stored
- HZ coords entered manually but not accepted...

**Comment by lukeIam** [comment] 2015-03-26 12:54
New try :wink:

**Comment by lukeIam** [comment] 2015-03-27 09:30
@Torsten- is it possible to create a package just for testing (without publishing it at the store?)

**Comment by Torsten-** [comment] 2015-03-27 10:14
Hi,

sure - look at Tools/create_chrome_package.sh - I just replace the 
Version-Number in manifest and build a zip-File.

Regards
   Torsten

**Comment by lukeIam** [comment] 2015-03-27 11:10
> sure - look at Tools/create_chrome_package.sh - I just replace the
> Version-Number in manifest and build a zip-File.

Yes, but there a little problem: Even if a pack a crx file, the newer chrome (release) versions won't load it.
They will only load extensions signed with a certificate from the store.

**Comment by lukeIam** [comment] 2015-03-27 11:39
[test version](https://github.com/lukeIam/GC_little_helper/blob/chromeTestExtension/GClhChromeTest.zip?raw=true)

Load unpacked extension in developer mode

**Comment by Torsten-** [comment] 2015-03-28 11:50
Does not look like I'm able to upload a test-version to the store :/

**Comment by galan64** [comment] 2015-03-28 18:06
Same problem over here.
Not able to add VIP list.
Uninstalled gclh and installed it again from chrome web store.
Updated chrome.
After that I could add 2 VIPS in stead of 1. 
My girlfriend sitting next to me has no problems at all.

**Comment by lukeIam** [comment] 2015-03-28 18:28
> My girlfriend sitting next to me has no problems at all.

It's a quota problem -> too frequent changes or to long templates causes the problem

> Uninstalled gclh and installed it 

try the [test version](https://github.com/lukeIam/GC_little_helper/blob/chromeTestExtension/GClhChromeTest.zip?raw=true)

load it as `unpacked extension` with `developer mode` enabled (see chrome://extensions)

**Comment by galan64** [comment] 2015-03-28 21:04
Thanks Luke, that worked for me.

**Comment by Cappa-d** [comment] 2015-03-28 22:37
so far test version solved the issues I had

**Comment by quizzmaster** [comment] 2015-04-06 19:27
I don't get #found# replaced any more with the test version :/

**Comment by lukeIam** [comment] 2015-04-06 19:29
@quizzmaster see #143

**Comment by lukeIam** [comment] 2015-05-03 20:55
Sould be fixed in the current release

**Closed by lukeIam** 2015-05-03 20:55 UTC
Labels: bug, Chrome, Fixed/Test

**Comment by xiefehl** [comment] 2015-05-08 06:47
IT alle Worms. Greta. Thnx

Op zondag 3 mei 2015 heeft lukeIam <notifications@github.com> het volgende
geschreven:
